Single-Lane-IDM:
  env: tsim-v0
  run: PPO
  checkpoint_freq: 50
  config:
    gamma: 0.99
    lambda: 0.95
    kl_coeff: 1.0
    num_sgd_iter: 32
    lr: 0.001
    vf_loss_coeff: 0.5
    clip_param: 0.2
    sgd_minibatch_size: 4096
    train_batch_size: 36864
    num_workers: 9
    num_gpus: 1
    grad_clip: 0.5
    horizon: 5500
    batch_mode: truncate_episodes
    callbacks:
      on_episode_end: None
    model:
      use_lstm: true
