config:
  render: true
  render-grid: true
  update-graphs: false
  update-graphs-method: occ
  external-controller: true
  time-period: 0.1
  trajec-file-path: None
  cell-size: 1
  view-size: 120
  fps: 60
  comm-mode: false
  frac-cells: 0.5
  region-width: 5
  collision-cost: -100
  use-vel: true
  max-vel: 25
  other-max-vel: 25
  hist-size: 1
  acc-noise: false
  reward-alpha: 0.1
  headway-thershold: 1 #second

